"""
This type stub file was generated by pyright.
"""

from .triangulation import *
from .tricontour import *
from .tritools import *
from .trifinder import *
from .triinterpolate import *
from .trirefine import *
from .tripcolor import *
from .triplot import *

"""
Unstructured triangular grid functions.
"""
