"""
This type stub file was generated by pyright.
"""

x: <Expression>
@+<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


@<Expression>
class :
     ...


