"""
This type stub file was generated by pyright.
"""

"""
A module for parsing and generating `fontconfig patterns`_.

.. _fontconfig patterns:
   https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
"""
family_punc = ...
family_unescape = ...
family_escape = ...
value_punc = ...
value_unescape = ...
value_escape = ...
class FontconfigPatternParser:
    """
    A simple pyparsing-based parser for `fontconfig patterns`_.

    .. _fontconfig patterns:
       https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
    """
    _constants = ...
    def __init__(self) -> None:
        ...
    
    def parse(self, pattern): # -> dict[Unknown, Unknown]:
        """
        Parse the given fontconfig *pattern* and return a dictionary
        of key/value pairs useful for initializing a
        `.font_manager.FontProperties` object.
        """
        ...
    


parse_fontconfig_pattern = ...
def generate_fontconfig_pattern(d): # -> str:
    """
    Given a dictionary of key/value pairs, generates a fontconfig
    pattern string.
    """
    ...

