"""
This type stub file was generated by pyright.
"""

import matplotlib
import matplotlib.image
from matplotlib import cbook, docstring, rcParams
from matplotlib.backend_bases import FigureCanvasBase
from matplotlib.figure import Figure
from matplotlib.rcsetup import interactive_bk as _interactive_bk
from matplotlib.artist import Artist
from matplotlib.axes import Axes

"""
`matplotlib.pyplot` is a state-based interface to matplotlib. It provides
an implicit,  MATLAB-like, way of plotting.  It also opens figures on your
screen, and acts as the figure GUI manager.

pyplot is mainly intended for interactive plots and simple cases of
programmatic plot generation::

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    plt.plot(x, y)

The explicit (object-oriented) API is recommended for complex plots, though
pyplot is still usually used to create the figure and often the axes in the
figure. See `.pyplot.figure`, `.pyplot.subplots`, and
`.pyplot.subplot_mosaic` to create figures, and
:doc:`Axes API <../axes_api>` for the plotting methods on an axes::

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    fig, ax = plt.subplots()
    ax.plot(x, y)
"""
_log = ...
_IP_REGISTERED = ...
_INSTALL_FIG_OBSERVER = ...
def install_repl_displayhook(): # -> None:
    """
    Install a repl display hook so that any stale figure are automatically
    redrawn when control is returned to the repl.

    This works both with IPython and with vanilla python shells.
    """
    ...

def uninstall_repl_displayhook(): # -> None:
    """
    Uninstall the Matplotlib display hook.

    .. warning::

       Need IPython >= 2 for this to work.  For IPython < 2 will raise a
       ``NotImplementedError``

    .. warning::

       If you are using vanilla python and have installed another
       display hook, this will reset ``sys.displayhook`` to what ever
       function was there when Matplotlib installed its displayhook,
       possibly discarding your changes.
    """
    ...

draw_all = ...
@_copy_docstring_and_deprecators(matplotlib.set_loglevel)
def set_loglevel(*args, **kwargs): # -> None:
    ...

@_copy_docstring_and_deprecators(Artist.findobj)
def findobj(o=..., match=..., include_self=...):
    ...

_backend_mod = ...
def switch_backend(newbackend): # -> None:
    """
    Close all open figures and set the Matplotlib backend.

    The argument is case-insensitive.  Switching to an interactive backend is
    possible only if no event loop for another interactive backend has started.
    Switching to and from non-interactive backends is always possible.

    Parameters
    ----------
    newbackend : str
        The name of the backend to use.
    """
    class backend_mod(matplotlib.backend_bases._Backend):
        ...
    
    

def new_figure_manager(*args, **kwargs):
    """Create a new figure manager instance."""
    ...

def draw_if_interactive(*args, **kwargs):
    """
    Redraw the current figure if in interactive mode.

    .. warning::

        End users will typically not have to call this function because the
        the interactive mode takes care of this.
    """
    ...

def show(*args, **kwargs):
    """
    Display all open figures.

    Parameters
    ----------
    block : bool, optional
        Whether to wait for all figures to be closed before returning.

        If `True` block and run the GUI main loop until all figure windows
        are closed.

        If `False` ensure that all figure windows are displayed and return
        immediately.  In this case, you are responsible for ensuring
        that the event loop is running to have responsive figures.

        Defaults to True in non-interactive mode and to False in interactive
        mode (see `.pyplot.isinteractive`).

    See Also
    --------
    ion : Enable interactive mode, which shows / updates the figure after
          every plotting command, so that calling ``show()`` is not necessary.
    ioff : Disable interactive mode.
    savefig : Save the figure to an image file instead of showing it on screen.

    Notes
    -----
    **Saving figures to file and showing a window at the same time**

    If you want an image file as well as a user interface window, use
    `.pyplot.savefig` before `.pyplot.show`. At the end of (a blocking)
    ``show()`` the figure is closed and thus unregistered from pyplot. Calling
    `.pyplot.savefig` afterwards would save a new and thus empty figure. This
    limitation of command order does not apply if the show is non-blocking or
    if you keep a reference to the figure and use `.Figure.savefig`.

    **Auto-show in jupyter notebooks**

    The jupyter backends (activated via ``%matplotlib inline``,
    ``%matplotlib notebook``, or ``%matplotlib widget``), call ``show()`` at
    the end of every cell by default. Thus, you usually don't have to call it
    explicitly there.
    """
    ...

def isinteractive():
    """
    Return whether plots are updated after every plotting command.

    The interactive mode is mainly useful if you build plots from the command
    line and want to see the effect of each command while you are building the
    figure.

    In interactive mode:

    - newly created figures will be shown immediately;
    - figures will automatically redraw on change;
    - `.pyplot.show` will not block by default.

    In non-interactive mode:

    - newly created figures and changes to figures will not be reflected until
      explicitly asked to be;
    - `.pyplot.show` will block by default.

    See Also
    --------
    ion : Enable interactive mode.
    ioff : Disable interactive mode.
    show : Show all figures (and maybe block).
    pause : Show all figures, and block for a time.
    """
    ...

class _IoffContext:
    """
    Context manager for `.ioff`.

    The state is changed in ``__init__()`` instead of ``__enter__()``. The
    latter is a no-op. This allows using `.ioff` both as a function and
    as a context.
    """
    def __init__(self) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


class _IonContext:
    """
    Context manager for `.ion`.

    The state is changed in ``__init__()`` instead of ``__enter__()``. The
    latter is a no-op. This allows using `.ion` both as a function and
    as a context.
    """
    def __init__(self) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


def ioff(): # -> _IoffContext:
    """
    Disable interactive mode.

    See `.pyplot.isinteractive` for more details.

    See Also
    --------
    ion : Enable interactive mode.
    isinteractive : Whether interactive mode is enabled.
    show : Show all figures (and maybe block).
    pause : Show all figures, and block for a time.

    Notes
    -----
    For a temporary change, this can be used as a context manager::

        # if interactive mode is on
        # then figures will be shown on creation
        plt.ion()
        # This figure will be shown immediately
        fig = plt.figure()

        with plt.ioff():
            # interactive mode will be off
            # figures will not automatically be shown
            fig2 = plt.figure()
            # ...

    To enable usage as a context manager, this function returns an
    ``_IoffContext`` object. The return value is not intended to be stored
    or accessed by the user.
    """
    ...

def ion(): # -> _IonContext:
    """
    Enable interactive mode.

    See `.pyplot.isinteractive` for more details.

    See Also
    --------
    ioff : Disable interactive mode.
    isinteractive : Whether interactive mode is enabled.
    show : Show all figures (and maybe block).
    pause : Show all figures, and block for a time.

    Notes
    -----
    For a temporary change, this can be used as a context manager::

        # if interactive mode is off
        # then figures will not be shown on creation
        plt.ioff()
        # This figure will not be shown immediately
        fig = plt.figure()

        with plt.ion():
            # interactive mode will be on
            # figures will automatically be shown
            fig2 = plt.figure()
            # ...

    To enable usage as a context manager, this function returns an
    ``_IonContext`` object. The return value is not intended to be stored
    or accessed by the user.
    """
    ...

def pause(interval): # -> None:
    """
    Run the GUI event loop for *interval* seconds.

    If there is an active figure, it will be updated and displayed before the
    pause, and the GUI event loop (if any) will run during the pause.

    This can be used for crude animation.  For more complex animation use
    :mod:`matplotlib.animation`.

    If there is no active figure, sleep for *interval* seconds instead.

    See Also
    --------
    matplotlib.animation : Proper animations
    show : Show all figures and optional block until all figures are closed.
    """
    ...

@_copy_docstring_and_deprecators(matplotlib.rc)
def rc(group, **kwargs): # -> None:
    ...

@_copy_docstring_and_deprecators(matplotlib.rc_context)
def rc_context(rc=..., fname=...): # -> _GeneratorContextManager[None]:
    ...

@_copy_docstring_and_deprecators(matplotlib.rcdefaults)
def rcdefaults(): # -> None:
    ...

@_copy_docstring_and_deprecators(matplotlib.artist.getp)
def getp(obj, *args, **kwargs):
    ...

@_copy_docstring_and_deprecators(matplotlib.artist.get)
def get(obj, *args, **kwargs):
    ...

@_copy_docstring_and_deprecators(matplotlib.artist.setp)
def setp(obj, *args, **kwargs):
    ...

def xkcd(scale=..., length=..., randomness=...): # -> _xkcd:
    """
    Turn on `xkcd <https://xkcd.com/>`_ sketch-style drawing mode.  This will
    only have effect on things drawn after this function is called.

    For best results, the "Humor Sans" font should be installed: it is
    not included with Matplotlib.

    Parameters
    ----------
    scale : float, optional
        The amplitude of the wiggle perpendicular to the source line.
    length : float, optional
        The length of the wiggle along the line.
    randomness : float, optional
        The scale factor by which the length is shrunken or expanded.

    Notes
    -----
    This function works by a number of rcParams, so it will probably
    override others you have set before.

    If you want the effects of this function to be temporary, it can
    be used as a context manager, for example::

        with plt.xkcd():
            # This figure will be in XKCD-style
            fig1 = plt.figure()
            # ...

        # This figure will be in regular style
        fig2 = plt.figure()
    """
    ...

class _xkcd:
    def __init__(self, scale, length, randomness) -> None:
        ...
    
    def __enter__(self): # -> Self@_xkcd:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


def figure(num=..., figsize=..., dpi=..., facecolor=..., edgecolor=..., frameon=..., FigureClass=..., clear=..., **kwargs):
    """
    Create a new figure, or activate an existing figure.

    Parameters
    ----------
    num : int or str or `.Figure`, optional
        A unique identifier for the figure.

        If a figure with that identifier already exists, this figure is made
        active and returned. An integer refers to the ``Figure.number``
        attribute, a string refers to the figure label.

        If there is no figure with the identifier or *num* is not given, a new
        figure is created, made active and returned.  If *num* is an int, it
        will be used for the ``Figure.number`` attribute, otherwise, an
        auto-generated integer value is used (starting at 1 and incremented
        for each new figure). If *num* is a string, the figure label and the
        window title is set to this value.

    figsize : (float, float), default: :rc:`figure.figsize`
        Width, height in inches.

    dpi : float, default: :rc:`figure.dpi`
        The resolution of the figure in dots-per-inch.

    facecolor : color, default: :rc:`figure.facecolor`
        The background color.

    edgecolor : color, default: :rc:`figure.edgecolor`
        The border color.

    frameon : bool, default: True
        If False, suppress drawing the figure frame.

    FigureClass : subclass of `~matplotlib.figure.Figure`
        Optionally use a custom `.Figure` instance.

    clear : bool, default: False
        If True and the figure already exists, then it is cleared.

    tight_layout : bool or dict, default: :rc:`figure.autolayout`
        If ``False`` use *subplotpars*. If ``True`` adjust subplot
        parameters using `.tight_layout` with default padding.
        When providing a dict containing the keys ``pad``, ``w_pad``,
        ``h_pad``, and ``rect``, the default `.tight_layout` paddings
        will be overridden.

    constrained_layout : bool, default: :rc:`figure.constrained_layout.use`
        If ``True`` use constrained layout to adjust positioning of plot
        elements.  Like ``tight_layout``, but designed to be more
        flexible.  See
        :doc:`/tutorials/intermediate/constrainedlayout_guide`
        for examples.  (Note: does not work with `add_subplot` or
        `~.pyplot.subplot2grid`.)


    **kwargs : optional
        See `~.matplotlib.figure.Figure` for other possible arguments.

    Returns
    -------
    `~matplotlib.figure.Figure`
        The `.Figure` instance returned will also be passed to
        new_figure_manager in the backends, which allows to hook custom
        `.Figure` classes into the pyplot interface. Additional kwargs will be
        passed to the `.Figure` init function.

    Notes
    -----
    If you are creating many figures, make sure you explicitly call
    `.pyplot.close` on the figures you are not using, because this will
    enable pyplot to properly clean up the memory.

    `~matplotlib.rcParams` defines the default values, which can be modified
    in the matplotlibrc file.
    """
    ...

def gcf():
    """
    Get the current figure.

    If there is currently no figure on the pyplot figure stack, a new one is
    created using `~.pyplot.figure()`.  (To test whether there is currently a
    figure on the pyplot figure stack, check whether `~.pyplot.get_fignums()`
    is empty.)
    """
    ...

def fignum_exists(num): # -> bool:
    """Return whether the figure with the given id exists."""
    ...

def get_fignums(): # -> list[Unknown]:
    """Return a list of existing figure numbers."""
    ...

def get_figlabels(): # -> list[Unknown]:
    """Return a list of existing figure labels."""
    ...

def get_current_fig_manager():
    """
    Return the figure manager of the current figure.

    The figure manager is a container for the actual backend-depended window
    that displays the figure on screen.

    If no current figure exists, a new one is created, and its figure
    manager is returned.

    Returns
    -------
    `.FigureManagerBase` or backend-dependent subclass thereof
    """
    ...

@_copy_docstring_and_deprecators(FigureCanvasBase.mpl_connect)
def connect(s, func):
    ...

@_copy_docstring_and_deprecators(FigureCanvasBase.mpl_disconnect)
def disconnect(cid):
    ...

def close(fig=...): # -> None:
    """
    Close a figure window.

    Parameters
    ----------
    fig : None or int or str or `.Figure`
        The figure to close. There are a number of ways to specify this:

        - *None*: the current figure
        - `.Figure`: the given `.Figure` instance
        - ``int``: a figure number
        - ``str``: a figure name
        - 'all': all figures

    """
    ...

def clf(): # -> None:
    """Clear the current figure."""
    ...

def draw(): # -> None:
    """
    Redraw the current figure.

    This is used to update a figure that has been altered, but not
    automatically re-drawn.  If interactive mode is on (via `.ion()`), this
    should be only rarely needed, but there may be ways to modify the state of
    a figure without marking it as "stale".  Please report these cases as bugs.

    This is equivalent to calling ``fig.canvas.draw_idle()``, where ``fig`` is
    the current figure.
    """
    ...

@_copy_docstring_and_deprecators(Figure.savefig)
def savefig(*args, **kwargs):
    ...

def figlegend(*args, **kwargs):
    ...

if Figure.legend.__doc__:
    ...
@docstring.dedent_interpd
def axes(arg=..., **kwargs):
    """
    Add an axes to the current figure and make it the current axes.

    Call signatures::

        plt.axes()
        plt.axes(rect, projection=None, polar=False, **kwargs)
        plt.axes(ax)

    Parameters
    ----------
    arg : None or 4-tuple
        The exact behavior of this function depends on the type:

        - *None*: A new full window axes is added using
          ``subplot(**kwargs)``.
        - 4-tuple of floats *rect* = ``[left, bottom, width, height]``.
          A new axes is added with dimensions *rect* in normalized
          (0, 1) units using `~.Figure.add_axes` on the current figure.

    projection : {None, 'aitoff', 'hammer', 'lambert', 'mollweide', \
'polar', 'rectilinear', str}, optional
        The projection type of the `~.axes.Axes`. *str* is the name of
        a custom projection, see `~matplotlib.projections`. The default
        None results in a 'rectilinear' projection.

    polar : bool, default: False
        If True, equivalent to projection='polar'.

    sharex, sharey : `~.axes.Axes`, optional
        Share the x or y `~matplotlib.axis` with sharex and/or sharey.
        The axis will have the same limits, ticks, and scale as the axis
        of the shared axes.

    label : str
        A label for the returned axes.

    Returns
    -------
    `~.axes.Axes`, or a subclass of `~.axes.Axes`
        The returned axes class depends on the projection used. It is
        `~.axes.Axes` if rectilinear projection is used and
        `.projections.polar.PolarAxes` if polar projection is used.

    Other Parameters
    ----------------
    **kwargs
        This method also takes the keyword arguments for
        the returned axes class. The keyword arguments for the
        rectilinear axes class `~.axes.Axes` can be found in
        the following table but there might also be other keyword
        arguments if another projection is used, see the actual axes
        class.

        %(Axes:kwdoc)s

    Notes
    -----
    If the figure already has a axes with key (*args*,
    *kwargs*) then it will simply make that axes current and
    return it.  This behavior is deprecated. Meanwhile, if you do
    not want this behavior (i.e., you want to force the creation of a
    new axes), you must use a unique set of args and kwargs.  The axes
    *label* attribute has been exposed for this purpose: if you want
    two axes that are otherwise identical to be added to the figure,
    make sure you give them unique labels.

    See Also
    --------
    .Figure.add_axes
    .pyplot.subplot
    .Figure.add_subplot
    .Figure.subplots
    .pyplot.subplots

    Examples
    --------
    ::

        # Creating a new full window axes
        plt.axes()

        # Creating a new axes with specified dimensions and some kwargs
        plt.axes((left, bottom, width, height), facecolor='w')
    """
    ...

def delaxes(ax=...): # -> None:
    """
    Remove an `~.axes.Axes` (defaulting to the current axes) from its figure.
    """
    ...

def sca(ax): # -> None:
    """
    Set the current Axes to *ax* and the current Figure to the parent of *ax*.
    """
    ...

def cla():
    """Clear the current axes."""
    ...

@docstring.dedent_interpd
def subplot(*args, **kwargs):
    """
    Add an Axes to the current figure or retrieve an existing Axes.

    This is a wrapper of `.Figure.add_subplot` which provides additional
    behavior when working with the implicit API (see the notes section).

    Call signatures::

       subplot(nrows, ncols, index, **kwargs)
       subplot(pos, **kwargs)
       subplot(**kwargs)
       subplot(ax)

    Parameters
    ----------
    *args : int, (int, int, *index*), or `.SubplotSpec`, default: (1, 1, 1)
        The position of the subplot described by one of

        - Three integers (*nrows*, *ncols*, *index*). The subplot will take the
          *index* position on a grid with *nrows* rows and *ncols* columns.
          *index* starts at 1 in the upper left corner and increases to the
          right. *index* can also be a two-tuple specifying the (*first*,
          *last*) indices (1-based, and including *last*) of the subplot, e.g.,
          ``fig.add_subplot(3, 1, (1, 2))`` makes a subplot that spans the
          upper 2/3 of the figure.
        - A 3-digit integer. The digits are interpreted as if given separately
          as three single-digit integers, i.e. ``fig.add_subplot(235)`` is the
          same as ``fig.add_subplot(2, 3, 5)``. Note that this can only be used
          if there are no more than 9 subplots.
        - A `.SubplotSpec`.

    projection : {None, 'aitoff', 'hammer', 'lambert', 'mollweide', \
'polar', 'rectilinear', str}, optional
        The projection type of the subplot (`~.axes.Axes`). *str* is the name
        of a custom projection, see `~matplotlib.projections`. The default
        None results in a 'rectilinear' projection.

    polar : bool, default: False
        If True, equivalent to projection='polar'.

    sharex, sharey : `~.axes.Axes`, optional
        Share the x or y `~matplotlib.axis` with sharex and/or sharey. The
        axis will have the same limits, ticks, and scale as the axis of the
        shared axes.

    label : str
        A label for the returned axes.

    Returns
    -------
    `.axes.SubplotBase`, or another subclass of `~.axes.Axes`

        The axes of the subplot. The returned axes base class depends on
        the projection used. It is `~.axes.Axes` if rectilinear projection
        is used and `.projections.polar.PolarAxes` if polar projection
        is used. The returned axes is then a subplot subclass of the
        base class.

    Other Parameters
    ----------------
    **kwargs
        This method also takes the keyword arguments for the returned axes
        base class; except for the *figure* argument. The keyword arguments
        for the rectilinear base class `~.axes.Axes` can be found in
        the following table but there might also be other keyword
        arguments if another projection is used.

        %(Axes:kwdoc)s

    Notes
    -----
    Creating a new Axes will delete any pre-existing Axes that
    overlaps with it beyond sharing a boundary::

        import matplotlib.pyplot as plt
        # plot a line, implicitly creating a subplot(111)
        plt.plot([1, 2, 3])
        # now create a subplot which represents the top plot of a grid
        # with 2 rows and 1 column. Since this subplot will overlap the
        # first, the plot (and its axes) previously created, will be removed
        plt.subplot(211)

    If you do not want this behavior, use the `.Figure.add_subplot` method
    or the `.pyplot.axes` function instead.

    If no *kwargs* are passed and there exists an Axes in the location
    specified by *args* then that Axes will be returned rather than a new
    Axes being created.

    If *kwargs* are passed and there exists an Axes in the location
    specified by *args*, the projection type is the same, and the
    *kwargs* match with the existing Axes, then the existing Axes is
    returned.  Otherwise a new Axes is created with the specified
    parameters.  We save a reference to the *kwargs* which we use
    for this comparison.  If any of the values in *kwargs* are
    mutable we will not detect the case where they are mutated.
    In these cases we suggest using `.Figure.add_subplot` and the
    explicit Axes API rather than the implicit pyplot API.

    See Also
    --------
    .Figure.add_subplot
    .pyplot.subplots
    .pyplot.axes
    .Figure.subplots

    Examples
    --------
    ::

        plt.subplot(221)

        # equivalent but more general
        ax1 = plt.subplot(2, 2, 1)

        # add a subplot with no frame
        ax2 = plt.subplot(222, frameon=False)

        # add a polar subplot
        plt.subplot(223, projection='polar')

        # add a red subplot that shares the x-axis with ax1
        plt.subplot(224, sharex=ax1, facecolor='red')

        # delete ax2 from the figure
        plt.delaxes(ax2)

        # add ax2 to the figure again
        plt.subplot(ax2)

        # make the first axes "current" again
        plt.subplot(221)

    """
    ...

def subplots(nrows=..., ncols=..., *, sharex=..., sharey=..., squeeze=..., subplot_kw=..., gridspec_kw=..., **fig_kw): # -> tuple[Unknown, Unknown]:
    """
    Create a figure and a set of subplots.

    This utility wrapper makes it convenient to create common layouts of
    subplots, including the enclosing figure object, in a single call.

    Parameters
    ----------
    nrows, ncols : int, default: 1
        Number of rows/columns of the subplot grid.

    sharex, sharey : bool or {'none', 'all', 'row', 'col'}, default: False
        Controls sharing of properties among x (*sharex*) or y (*sharey*)
        axes:

        - True or 'all': x- or y-axis will be shared among all subplots.
        - False or 'none': each subplot x- or y-axis will be independent.
        - 'row': each subplot row will share an x- or y-axis.
        - 'col': each subplot column will share an x- or y-axis.

        When subplots have a shared x-axis along a column, only the x tick
        labels of the bottom subplot are created. Similarly, when subplots
        have a shared y-axis along a row, only the y tick labels of the first
        column subplot are created. To later turn other subplots' ticklabels
        on, use `~matplotlib.axes.Axes.tick_params`.

        When subplots have a shared axis that has units, calling
        `~matplotlib.axis.Axis.set_units` will update each axis with the
        new units.

    squeeze : bool, default: True
        - If True, extra dimensions are squeezed out from the returned
          array of `~matplotlib.axes.Axes`:

          - if only one subplot is constructed (nrows=ncols=1), the
            resulting single Axes object is returned as a scalar.
          - for Nx1 or 1xM subplots, the returned object is a 1D numpy
            object array of Axes objects.
          - for NxM, subplots with N>1 and M>1 are returned as a 2D array.

        - If False, no squeezing at all is done: the returned Axes object is
          always a 2D array containing Axes instances, even if it ends up
          being 1x1.

    subplot_kw : dict, optional
        Dict with keywords passed to the
        `~matplotlib.figure.Figure.add_subplot` call used to create each
        subplot.

    gridspec_kw : dict, optional
        Dict with keywords passed to the `~matplotlib.gridspec.GridSpec`
        constructor used to create the grid the subplots are placed on.

    **fig_kw
        All additional keyword arguments are passed to the
        `.pyplot.figure` call.

    Returns
    -------
    fig : `~.figure.Figure`

    ax : `.axes.Axes` or array of Axes
        *ax* can be either a single `~matplotlib.axes.Axes` object or an
        array of Axes objects if more than one subplot was created.  The
        dimensions of the resulting array can be controlled with the squeeze
        keyword, see above.

        Typical idioms for handling the return value are::

            # using the variable ax for single a Axes
            fig, ax = plt.subplots()

            # using the variable axs for multiple Axes
            fig, axs = plt.subplots(2, 2)

            # using tuple unpacking for multiple Axes
            fig, (ax1, ax2) = plt.subplots(1, 2)
            fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2)

        The names ``ax`` and pluralized ``axs`` are preferred over ``axes``
        because for the latter it's not clear if it refers to a single
        `~.axes.Axes` instance or a collection of these.

    See Also
    --------
    .pyplot.figure
    .pyplot.subplot
    .pyplot.axes
    .Figure.subplots
    .Figure.add_subplot

    Examples
    --------
    ::

        # First create some toy data:
        x = np.linspace(0, 2*np.pi, 400)
        y = np.sin(x**2)

        # Create just a figure and only one subplot
        fig, ax = plt.subplots()
        ax.plot(x, y)
        ax.set_title('Simple plot')

        # Create two subplots and unpack the output array immediately
        f, (ax1, ax2) = plt.subplots(1, 2, sharey=True)
        ax1.plot(x, y)
        ax1.set_title('Sharing Y axis')
        ax2.scatter(x, y)

        # Create four polar axes and access them through the returned array
        fig, axs = plt.subplots(2, 2, subplot_kw=dict(projection="polar"))
        axs[0, 0].plot(x, y)
        axs[1, 1].scatter(x, y)

        # Share a X axis with each column of subplots
        plt.subplots(2, 2, sharex='col')

        # Share a Y axis with each row of subplots
        plt.subplots(2, 2, sharey='row')

        # Share both X and Y axes with all subplots
        plt.subplots(2, 2, sharex='all', sharey='all')

        # Note that this is the same as
        plt.subplots(2, 2, sharex=True, sharey=True)

        # Create figure number 10 with a single subplot
        # and clears it if it already exists.
        fig, ax = plt.subplots(num=10, clear=True)

    """
    ...

def subplot_mosaic(mosaic, *, sharex=..., sharey=..., subplot_kw=..., gridspec_kw=..., empty_sentinel=..., **fig_kw): # -> tuple[Unknown, Unknown]:
    """
    Build a layout of Axes based on ASCII art or nested lists.

    This is a helper function to build complex GridSpec layouts visually.

    .. note ::

       This API is provisional and may be revised in the future based on
       early user feedback.

    Parameters
    ----------
    mosaic : list of list of {hashable or nested} or str

        A visual layout of how you want your Axes to be arranged
        labeled as strings.  For example ::

           x = [['A panel', 'A panel', 'edge'],
                ['C panel', '.',       'edge']]

        produces 4 axes:

        - 'A panel' which is 1 row high and spans the first two columns
        - 'edge' which is 2 rows high and is on the right edge
        - 'C panel' which in 1 row and 1 column wide in the bottom left
        - a blank space 1 row and 1 column wide in the bottom center

        Any of the entries in the layout can be a list of lists
        of the same form to create nested layouts.

        If input is a str, then it must be of the form ::

          '''
          AAE
          C.E
          '''

        where each character is a column and each line is a row.
        This only allows only single character Axes labels and does
        not allow nesting but is very terse.

    sharex, sharey : bool, default: False
        If True, the x-axis (*sharex*) or y-axis (*sharey*) will be shared
        among all subplots.  In that case, tick label visibility and axis units
        behave as for `subplots`.  If False, each subplot's x- or y-axis will
        be independent.

    subplot_kw : dict, optional
        Dictionary with keywords passed to the `.Figure.add_subplot` call
        used to create each subplot.

    gridspec_kw : dict, optional
        Dictionary with keywords passed to the `.GridSpec` constructor used
        to create the grid the subplots are placed on.

    empty_sentinel : object, optional
        Entry in the layout to mean "leave this space empty".  Defaults
        to ``'.'``. Note, if *layout* is a string, it is processed via
        `inspect.cleandoc` to remove leading white space, which may
        interfere with using white-space as the empty sentinel.

    **fig_kw
        All additional keyword arguments are passed to the
        `.pyplot.figure` call.

    Returns
    -------
    fig : `~.figure.Figure`
       The new figure

    dict[label, Axes]
       A dictionary mapping the labels to the Axes objects.  The order of
       the axes is left-to-right and top-to-bottom of their position in the
       total layout.

    """
    ...

def subplot2grid(shape, loc, rowspan=..., colspan=..., fig=..., **kwargs):
    """
    Create a subplot at a specific location inside a regular grid.

    Parameters
    ----------
    shape : (int, int)
        Number of rows and of columns of the grid in which to place axis.
    loc : (int, int)
        Row number and column number of the axis location within the grid.
    rowspan : int, default: 1
        Number of rows for the axis to span downwards.
    colspan : int, default: 1
        Number of columns for the axis to span to the right.
    fig : `.Figure`, optional
        Figure to place the subplot in. Defaults to the current figure.
    **kwargs
        Additional keyword arguments are handed to `~.Figure.add_subplot`.

    Returns
    -------
    `.axes.SubplotBase`, or another subclass of `~.axes.Axes`

        The axes of the subplot.  The returned axes base class depends on the
        projection used.  It is `~.axes.Axes` if rectilinear projection is used
        and `.projections.polar.PolarAxes` if polar projection is used.  The
        returned axes is then a subplot subclass of the base class.

    Notes
    -----
    The following call ::

        ax = subplot2grid((nrows, ncols), (row, col), rowspan, colspan)

    is identical to ::

        fig = gcf()
        gs = fig.add_gridspec(nrows, ncols)
        ax = fig.add_subplot(gs[row:row+rowspan, col:col+colspan])
    """
    ...

def twinx(ax=...):
    """
    Make and return a second axes that shares the *x*-axis.  The new axes will
    overlay *ax* (or the current axes if *ax* is *None*), and its ticks will be
    on the right.

    Examples
    --------
    :doc:`/gallery/subplots_axes_and_figures/two_scales`
    """
    ...

def twiny(ax=...):
    """
    Make and return a second axes that shares the *y*-axis.  The new axes will
    overlay *ax* (or the current axes if *ax* is *None*), and its ticks will be
    on the top.

    Examples
    --------
    :doc:`/gallery/subplots_axes_and_figures/two_scales`
    """
    ...

def subplot_tool(targetfig=...):
    """
    Launch a subplot tool window for a figure.

    Returns
    -------
    `matplotlib.widgets.SubplotTool`
    """
    ...

def box(on=...): # -> None:
    """
    Turn the axes box on or off on the current axes.

    Parameters
    ----------
    on : bool or None
        The new `~matplotlib.axes.Axes` box state. If ``None``, toggle
        the state.

    See Also
    --------
    :meth:`matplotlib.axes.Axes.set_frame_on`
    :meth:`matplotlib.axes.Axes.get_frame_on`
    """
    ...

def xlim(*args, **kwargs):
    """
    Get or set the x limits of the current axes.

    Call signatures::

        left, right = xlim()  # return the current xlim
        xlim((left, right))   # set the xlim to left, right
        xlim(left, right)     # set the xlim to left, right

    If you do not specify args, you can pass *left* or *right* as kwargs,
    i.e.::

        xlim(right=3)  # adjust the right leaving left unchanged
        xlim(left=1)  # adjust the left leaving right unchanged

    Setting limits turns autoscaling off for the x-axis.

    Returns
    -------
    left, right
        A tuple of the new x-axis limits.

    Notes
    -----
    Calling this function with no arguments (e.g. ``xlim()``) is the pyplot
    equivalent of calling `~.Axes.get_xlim` on the current axes.
    Calling this function with arguments is the pyplot equivalent of calling
    `~.Axes.set_xlim` on the current axes. All arguments are passed though.
    """
    ...

def ylim(*args, **kwargs):
    """
    Get or set the y-limits of the current axes.

    Call signatures::

        bottom, top = ylim()  # return the current ylim
        ylim((bottom, top))   # set the ylim to bottom, top
        ylim(bottom, top)     # set the ylim to bottom, top

    If you do not specify args, you can alternatively pass *bottom* or
    *top* as kwargs, i.e.::

        ylim(top=3)  # adjust the top leaving bottom unchanged
        ylim(bottom=1)  # adjust the bottom leaving top unchanged

    Setting limits turns autoscaling off for the y-axis.

    Returns
    -------
    bottom, top
        A tuple of the new y-axis limits.

    Notes
    -----
    Calling this function with no arguments (e.g. ``ylim()``) is the pyplot
    equivalent of calling `~.Axes.get_ylim` on the current axes.
    Calling this function with arguments is the pyplot equivalent of calling
    `~.Axes.set_ylim` on the current axes. All arguments are passed though.
    """
    ...

def xticks(ticks=..., labels=..., **kwargs): # -> tuple[Unknown, Unknown]:
    """
    Get or set the current tick locations and labels of the x-axis.

    Pass no arguments to return the current values without modifying them.

    Parameters
    ----------
    ticks : array-like, optional
        The list of xtick locations.  Passing an empty list removes all xticks.
    labels : array-like, optional
        The labels to place at the given *ticks* locations.  This argument can
        only be passed if *ticks* is passed as well.
    **kwargs
        `.Text` properties can be used to control the appearance of the labels.

    Returns
    -------
    locs
        The list of xtick locations.
    labels
        The list of xlabel `.Text` objects.

    Notes
    -----
    Calling this function with no arguments (e.g. ``xticks()``) is the pyplot
    equivalent of calling `~.Axes.get_xticks` and `~.Axes.get_xticklabels` on
    the current axes.
    Calling this function with arguments is the pyplot equivalent of calling
    `~.Axes.set_xticks` and `~.Axes.set_xticklabels` on the current axes.

    Examples
    --------
    >>> locs, labels = xticks()  # Get the current locations and labels.
    >>> xticks(np.arange(0, 1, step=0.2))  # Set label locations.
    >>> xticks(np.arange(3), ['Tom', 'Dick', 'Sue'])  # Set text labels.
    >>> xticks([0, 1, 2], ['January', 'February', 'March'],
    ...        rotation=20)  # Set text labels and properties.
    >>> xticks([])  # Disable xticks.
    """
    ...

def yticks(ticks=..., labels=..., **kwargs): # -> tuple[Unknown, Unknown]:
    """
    Get or set the current tick locations and labels of the y-axis.

    Pass no arguments to return the current values without modifying them.

    Parameters
    ----------
    ticks : array-like, optional
        The list of ytick locations.  Passing an empty list removes all yticks.
    labels : array-like, optional
        The labels to place at the given *ticks* locations.  This argument can
        only be passed if *ticks* is passed as well.
    **kwargs
        `.Text` properties can be used to control the appearance of the labels.

    Returns
    -------
    locs
        The list of ytick locations.
    labels
        The list of ylabel `.Text` objects.

    Notes
    -----
    Calling this function with no arguments (e.g. ``yticks()``) is the pyplot
    equivalent of calling `~.Axes.get_yticks` and `~.Axes.get_yticklabels` on
    the current axes.
    Calling this function with arguments is the pyplot equivalent of calling
    `~.Axes.set_yticks` and `~.Axes.set_yticklabels` on the current axes.

    Examples
    --------
    >>> locs, labels = yticks()  # Get the current locations and labels.
    >>> yticks(np.arange(0, 1, step=0.2))  # Set label locations.
    >>> yticks(np.arange(3), ['Tom', 'Dick', 'Sue'])  # Set text labels.
    >>> yticks([0, 1, 2], ['January', 'February', 'March'],
    ...        rotation=45)  # Set text labels and properties.
    >>> yticks([])  # Disable yticks.
    """
    ...

def rgrids(radii=..., labels=..., angle=..., fmt=..., **kwargs): # -> tuple[silent_list, list[Unknown]]:
    """
    Get or set the radial gridlines on the current polar plot.

    Call signatures::

     lines, labels = rgrids()
     lines, labels = rgrids(radii, labels=None, angle=22.5, fmt=None, **kwargs)

    When called with no arguments, `.rgrids` simply returns the tuple
    (*lines*, *labels*). When called with arguments, the labels will
    appear at the specified radial distances and angle.

    Parameters
    ----------
    radii : tuple with floats
        The radii for the radial gridlines

    labels : tuple with strings or None
        The labels to use at each radial gridline. The
        `matplotlib.ticker.ScalarFormatter` will be used if None.

    angle : float
        The angular position of the radius labels in degrees.

    fmt : str or None
        Format string used in `matplotlib.ticker.FormatStrFormatter`.
        For example '%f'.

    Returns
    -------
    lines : list of `.lines.Line2D`
        The radial gridlines.

    labels : list of `.text.Text`
        The tick labels.

    Other Parameters
    ----------------
    **kwargs
        *kwargs* are optional `.Text` properties for the labels.

    See Also
    --------
    .pyplot.thetagrids
    .projections.polar.PolarAxes.set_rgrids
    .Axis.get_gridlines
    .Axis.get_ticklabels

    Examples
    --------
    ::

      # set the locations of the radial gridlines
      lines, labels = rgrids( (0.25, 0.5, 1.0) )

      # set the locations and labels of the radial gridlines
      lines, labels = rgrids( (0.25, 0.5, 1.0), ('Tom', 'Dick', 'Harry' ))
    """
    ...

def thetagrids(angles=..., labels=..., fmt=..., **kwargs): # -> tuple[silent_list, list[Unknown]]:
    """
    Get or set the theta gridlines on the current polar plot.

    Call signatures::

     lines, labels = thetagrids()
     lines, labels = thetagrids(angles, labels=None, fmt=None, **kwargs)

    When called with no arguments, `.thetagrids` simply returns the tuple
    (*lines*, *labels*). When called with arguments, the labels will
    appear at the specified angles.

    Parameters
    ----------
    angles : tuple with floats, degrees
        The angles of the theta gridlines.

    labels : tuple with strings or None
        The labels to use at each radial gridline. The
        `.projections.polar.ThetaFormatter` will be used if None.

    fmt : str or None
        Format string used in `matplotlib.ticker.FormatStrFormatter`.
        For example '%f'. Note that the angle in radians will be used.

    Returns
    -------
    lines : list of `.lines.Line2D`
        The theta gridlines.

    labels : list of `.text.Text`
        The tick labels.

    Other Parameters
    ----------------
    **kwargs
        *kwargs* are optional `.Text` properties for the labels.

    See Also
    --------
    .pyplot.rgrids
    .projections.polar.PolarAxes.set_thetagrids
    .Axis.get_gridlines
    .Axis.get_ticklabels

    Examples
    --------
    ::

      # set the locations of the angular gridlines
      lines, labels = thetagrids(range(45, 360, 90))

      # set the locations and labels of the angular gridlines
      lines, labels = thetagrids(range(45, 360, 90), ('NE', 'NW', 'SW', 'SE'))
    """
    ...

def plotting(): # -> None:
    ...

def get_plot_commands(): # -> list[str]:
    """
    Get a sorted list of all of the plotting commands.
    """
    ...

@_copy_docstring_and_deprecators(Figure.colorbar)
def colorbar(mappable=..., cax=..., ax=..., **kw):
    ...

def clim(vmin=..., vmax=...): # -> None:
    """
    Set the color limits of the current image.

    If either *vmin* or *vmax* is None, the image min/max respectively
    will be used for color scaling.

    If you want to set the clim of multiple images, use
    `~.ScalarMappable.set_clim` on every image, for example::

      for im in gca().get_images():
          im.set_clim(0, 0.5)

    """
    ...

def set_cmap(cmap): # -> None:
    """
    Set the default colormap, and applies it to the current image if any.

    Parameters
    ----------
    cmap : `~matplotlib.colors.Colormap` or str
        A colormap instance or the name of a registered colormap.

    See Also
    --------
    colormaps
    matplotlib.cm.register_cmap
    matplotlib.cm.get_cmap
    """
    ...

@_copy_docstring_and_deprecators(matplotlib.image.imread)
def imread(fname, format=...):
    ...

@_copy_docstring_and_deprecators(matplotlib.image.imsave)
def imsave(fname, arr, **kwargs):
    ...

def matshow(A, fignum=..., **kwargs):
    """
    Display an array as a matrix in a new figure window.

    The origin is set at the upper left hand corner and rows (first
    dimension of the array) are displayed horizontally.  The aspect
    ratio of the figure window is that of the array, unless this would
    make an excessively short or narrow figure.

    Tick labels for the xaxis are placed on top.

    Parameters
    ----------
    A : 2D array-like
        The matrix to be displayed.

    fignum : None or int or False
        If *None*, create a new figure window with automatic numbering.

        If a nonzero integer, draw into the figure with the given number
        (create it if it does not exist).

        If 0, use the current axes (or create one if it does not exist).

        .. note::

           Because of how `.Axes.matshow` tries to set the figure aspect
           ratio to be the one of the array, strange things may happen if you
           reuse an existing figure.

    Returns
    -------
    `~matplotlib.image.AxesImage`

    Other Parameters
    ----------------
    **kwargs : `~matplotlib.axes.Axes.imshow` arguments

    """
    ...

def polar(*args, **kwargs): # -> list[Unknown]:
    """
    Make a polar plot.

    call signature::

      polar(theta, r, **kwargs)

    Multiple *theta*, *r* arguments are supported, with format strings, as in
    `plot`.
    """
    ...

if (rcParams["backend_fallback"] and dict.__getitem__(rcParams, "backend") in (set(_interactive_bk) - 'WebAgg', 'nbAgg') and cbook._get_running_interactive_framework()):
    ...
@_copy_docstring_and_deprecators(Figure.figimage)
def figimage(X, xo=..., yo=..., alpha=..., norm=..., cmap=..., vmin=..., vmax=..., origin=..., resize=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Figure.text)
def figtext(x, y, s, fontdict=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Figure.gca)
def gca(**kwargs):
    ...

@_copy_docstring_and_deprecators(Figure._gci)
def gci():
    ...

@_copy_docstring_and_deprecators(Figure.ginput)
def ginput(n=..., timeout=..., show_clicks=..., mouse_add=..., mouse_pop=..., mouse_stop=...):
    ...

@_copy_docstring_and_deprecators(Figure.subplots_adjust)
def subplots_adjust(left=..., bottom=..., right=..., top=..., wspace=..., hspace=...):
    ...

@_copy_docstring_and_deprecators(Figure.suptitle)
def suptitle(t, **kwargs):
    ...

@_copy_docstring_and_deprecators(Figure.tight_layout)
def tight_layout(*, pad=..., h_pad=..., w_pad=..., rect=...):
    ...

@_copy_docstring_and_deprecators(Figure.waitforbuttonpress)
def waitforbuttonpress(timeout=...):
    ...

@_copy_docstring_and_deprecators(Axes.acorr)
def acorr(x, *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.angle_spectrum)
def angle_spectrum(x, Fs=..., Fc=..., window=..., pad_to=..., sides=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.annotate)
def annotate(text, xy, *args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.arrow)
def arrow(x, y, dx, dy, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.autoscale)
def autoscale(enable=..., axis=..., tight=...):
    ...

@_copy_docstring_and_deprecators(Axes.axhline)
def axhline(y=..., xmin=..., xmax=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.axhspan)
def axhspan(ymin, ymax, xmin=..., xmax=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.axis)
def axis(*args, emit=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.axline)
def axline(xy1, xy2=..., *, slope=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.axvline)
def axvline(x=..., ymin=..., ymax=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.axvspan)
def axvspan(xmin, xmax, ymin=..., ymax=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.bar)
def bar(x, height, width=..., bottom=..., *, align=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.barbs)
def barbs(*args, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.barh)
def barh(y, width, height=..., left=..., *, align=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.bar_label)
def bar_label(container, labels=..., *, fmt=..., label_type=..., padding=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.boxplot)
def boxplot(x, notch=..., sym=..., vert=..., whis=..., positions=..., widths=..., patch_artist=..., bootstrap=..., usermedians=..., conf_intervals=..., meanline=..., showmeans=..., showcaps=..., showbox=..., showfliers=..., boxprops=..., labels=..., flierprops=..., medianprops=..., meanprops=..., capprops=..., whiskerprops=..., manage_ticks=..., autorange=..., zorder=..., *, data=...):
    ...

@_copy_docstring_and_deprecators(Axes.broken_barh)
def broken_barh(xranges, yrange, *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.clabel)
def clabel(CS, levels=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.cohere)
def cohere(x, y, NFFT=..., Fs=..., Fc=..., detrend=..., window=..., noverlap=..., pad_to=..., sides=..., scale_by_freq=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.contour)
def contour(*args, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.contourf)
def contourf(*args, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.csd)
def csd(x, y, NFFT=..., Fs=..., Fc=..., detrend=..., window=..., noverlap=..., pad_to=..., sides=..., scale_by_freq=..., return_line=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.errorbar)
def errorbar(x, y, yerr=..., xerr=..., fmt=..., ecolor=..., elinewidth=..., capsize=..., barsabove=..., lolims=..., uplims=..., xlolims=..., xuplims=..., errorevery=..., capthick=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.eventplot)
def eventplot(positions, orientation=..., lineoffsets=..., linelengths=..., linewidths=..., colors=..., linestyles=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.fill)
def fill(*args, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.fill_between)
def fill_between(x, y1, y2=..., where=..., interpolate=..., step=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.fill_betweenx)
def fill_betweenx(y, x1, x2=..., where=..., step=..., interpolate=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.grid)
def grid(visible=..., which=..., axis=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.hexbin)
def hexbin(x, y, C=..., gridsize=..., bins=..., xscale=..., yscale=..., extent=..., cmap=..., norm=..., vmin=..., vmax=..., alpha=..., linewidths=..., edgecolors=..., reduce_C_function=..., mincnt=..., marginals=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.hist)
def hist(x, bins=..., range=..., density=..., weights=..., cumulative=..., bottom=..., histtype=..., align=..., orientation=..., rwidth=..., log=..., color=..., label=..., stacked=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.stairs)
def stairs(values, edges=..., *, orientation=..., baseline=..., fill=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.hist2d)
def hist2d(x, y, bins=..., range=..., density=..., weights=..., cmin=..., cmax=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.hlines)
def hlines(y, xmin, xmax, colors=..., linestyles=..., label=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.imshow)
def imshow(X, cmap=..., norm=..., aspect=..., interpolation=..., alpha=..., vmin=..., vmax=..., origin=..., extent=..., *, interpolation_stage=..., filternorm=..., filterrad=..., resample=..., url=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.legend)
def legend(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.locator_params)
def locator_params(axis=..., tight=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.loglog)
def loglog(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.magnitude_spectrum)
def magnitude_spectrum(x, Fs=..., Fc=..., window=..., pad_to=..., sides=..., scale=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.margins)
def margins(*margins, x=..., y=..., tight=...):
    ...

@_copy_docstring_and_deprecators(Axes.minorticks_off)
def minorticks_off():
    ...

@_copy_docstring_and_deprecators(Axes.minorticks_on)
def minorticks_on():
    ...

@_copy_docstring_and_deprecators(Axes.pcolor)
def pcolor(*args, shading=..., alpha=..., norm=..., cmap=..., vmin=..., vmax=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.pcolormesh)
def pcolormesh(*args, alpha=..., norm=..., cmap=..., vmin=..., vmax=..., shading=..., antialiased=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.phase_spectrum)
def phase_spectrum(x, Fs=..., Fc=..., window=..., pad_to=..., sides=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.pie)
def pie(x, explode=..., labels=..., colors=..., autopct=..., pctdistance=..., shadow=..., labeldistance=..., startangle=..., radius=..., counterclock=..., wedgeprops=..., textprops=..., center=..., frame=..., rotatelabels=..., *, normalize=..., data=...):
    ...

@_copy_docstring_and_deprecators(Axes.plot)
def plot(*args, scalex=..., scaley=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.plot_date)
def plot_date(x, y, fmt=..., tz=..., xdate=..., ydate=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.psd)
def psd(x, NFFT=..., Fs=..., Fc=..., detrend=..., window=..., noverlap=..., pad_to=..., sides=..., scale_by_freq=..., return_line=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.quiver)
def quiver(*args, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.quiverkey)
def quiverkey(Q, X, Y, U, label, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.scatter)
def scatter(x, y, s=..., c=..., marker=..., cmap=..., norm=..., vmin=..., vmax=..., alpha=..., linewidths=..., *, edgecolors=..., plotnonfinite=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.semilogx)
def semilogx(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.semilogy)
def semilogy(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.specgram)
def specgram(x, NFFT=..., Fs=..., Fc=..., detrend=..., window=..., noverlap=..., cmap=..., xextent=..., pad_to=..., sides=..., scale_by_freq=..., mode=..., scale=..., vmin=..., vmax=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.spy)
def spy(Z, precision=..., marker=..., markersize=..., aspect=..., origin=..., **kwargs): # -> ScalarMappable:
    ...

@_copy_docstring_and_deprecators(Axes.stackplot)
def stackplot(x, *args, labels=..., colors=..., baseline=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.stem)
def stem(*args, linefmt=..., markerfmt=..., basefmt=..., bottom=..., label=..., use_line_collection=..., orientation=..., data=...):
    ...

@_copy_docstring_and_deprecators(Axes.step)
def step(x, y, *args, where=..., data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.streamplot)
def streamplot(x, y, u, v, density=..., linewidth=..., color=..., cmap=..., norm=..., arrowsize=..., arrowstyle=..., minlength=..., transform=..., zorder=..., start_points=..., maxlength=..., integration_direction=..., *, data=...):
    ...

@_copy_docstring_and_deprecators(Axes.table)
def table(cellText=..., cellColours=..., cellLoc=..., colWidths=..., rowLabels=..., rowColours=..., rowLoc=..., colLabels=..., colColours=..., colLoc=..., loc=..., bbox=..., edges=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.text)
def text(x, y, s, fontdict=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.tick_params)
def tick_params(axis=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.ticklabel_format)
def ticklabel_format(*, axis=..., style=..., scilimits=..., useOffset=..., useLocale=..., useMathText=...):
    ...

@_copy_docstring_and_deprecators(Axes.tricontour)
def tricontour(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.tricontourf)
def tricontourf(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.tripcolor)
def tripcolor(*args, alpha=..., norm=..., cmap=..., vmin=..., vmax=..., shading=..., facecolors=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.triplot)
def triplot(*args, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.violinplot)
def violinplot(dataset, positions=..., vert=..., widths=..., showmeans=..., showextrema=..., showmedians=..., quantiles=..., points=..., bw_method=..., *, data=...):
    ...

@_copy_docstring_and_deprecators(Axes.vlines)
def vlines(x, ymin, ymax, colors=..., linestyles=..., label=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.xcorr)
def xcorr(x, y, normed=..., detrend=..., usevlines=..., maxlags=..., *, data=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes._sci)
def sci(im):
    ...

@_copy_docstring_and_deprecators(Axes.set_title)
def title(label, fontdict=..., loc=..., pad=..., *, y=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.set_xlabel)
def xlabel(xlabel, fontdict=..., labelpad=..., *, loc=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.set_ylabel)
def ylabel(ylabel, fontdict=..., labelpad=..., *, loc=..., **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.set_xscale)
def xscale(value, **kwargs):
    ...

@_copy_docstring_and_deprecators(Axes.set_yscale)
def yscale(value, **kwargs):
    ...

def autumn(): # -> None:
    ...

def bone(): # -> None:
    ...

def cool(): # -> None:
    ...

def copper(): # -> None:
    ...

def flag(): # -> None:
    ...

def gray(): # -> None:
    ...

def hot(): # -> None:
    ...

def hsv(): # -> None:
    ...

def jet(): # -> None:
    ...

def pink(): # -> None:
    ...

def prism(): # -> None:
    ...

def spring(): # -> None:
    ...

def summer(): # -> None:
    ...

def winter(): # -> None:
    ...

def magma(): # -> None:
    ...

def inferno(): # -> None:
    ...

def plasma(): # -> None:
    ...

def viridis(): # -> None:
    ...

def nipy_spectral(): # -> None:
    ...

